// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import AdvancedFiltersController from "controllers/advanced_filters_controller"
application.register("advanced-filters", AdvancedFiltersController)

import AutocompleteController from "controllers/autocomplete_controller"
application.register("autocomplete", AutocompleteController)

import CardSwiperController from "controllers/card_swiper_controller"
application.register("card-swiper", CardSwiperController)

import ClickableCardController from "controllers/clickable_card_controller"
application.register("clickable-card", ClickableCardController)

import CodeSearchController from "controllers/code_search_controller"
application.register("code-search", CodeSearchController)

import CurrencyMaskController from "controllers/currency_mask_controller"
application.register("currency-mask", CurrencyMaskController)

import DynamicListController from "controllers/dynamic_list_controller"
application.register("dynamic-list", DynamicListController)

import FavoritesController from "controllers/favorites_controller"
application.register("favorites", FavoritesController)

import FiltersController from "controllers/filters_controller"
application.register("filters", FiltersController)

import HelloController from "controllers/hello_controller"
application.register("hello", HelloController)

import HeroSliderController from "controllers/hero_slider_controller"
application.register("hero-slider", HeroSliderController)

import LeadCaptureController from "controllers/lead_capture_controller"
application.register("lead-capture", LeadCaptureController)

import MaskController from "controllers/mask_controller"
application.register("mask", MaskController)

import NavbarController from "controllers/navbar_controller"
application.register("navbar", NavbarController)

import NestedFormController from "controllers/nested_form_controller"
application.register("nested-form", NestedFormController)

import PhotoCarouselController from "controllers/photo_carousel_controller"
application.register("photo-carousel", PhotoCarouselController)

import PhotoGalleryController from "controllers/photo_gallery_controller"
application.register("photo-gallery", PhotoGalleryController)

import PhotoUploadController from "controllers/photo_upload_controller"
application.register("photo-upload", PhotoUploadController)

import PropertyCarouselController from "controllers/property_carousel_controller"
application.register("property-carousel", PropertyCarouselController)

import PropertyPagePreviewController from "controllers/property_page_preview_controller"
application.register("property-page-preview", PropertyPagePreviewController)

import ScrollVisibilityController from "controllers/scroll_visibility_controller"
application.register("scroll-visibility", ScrollVisibilityController)

import SearchFormController from "controllers/search_form_controller"
application.register("search-form", SearchFormController)

import SearchTabsController from "controllers/search_tabs_controller"
application.register("search-tabs", SearchTabsController)

import ShareController from "controllers/share_controller"
application.register("share", ShareController)

import SidebarController from "controllers/sidebar_controller"
application.register("sidebar", SidebarController)

import TagInputController from "controllers/tag_input_controller"
application.register("tag-input", TagInputController)

import TomSelectController from "controllers/tom_select_controller"
application.register("tom-select", TomSelectController)

import TransactionToggleController from "controllers/transaction_toggle_controller"
application.register("transaction-toggle", TransactionToggleController)
